spring:
  profiles:
    # Wenn nichts anderes angegeben verwenden wir MySQL als Datenbank
    active: mysql
  jpa:
    show-sql: true
  application:
    name: RoterOktoberServer

liquibase:
  change-log: classpath:/db/changelog/changelog.xml
  default-schema: roteroktober
logging:
  level:
    org:
      hibernate: info