spring:
  datasource:
    url: jdbc:mysql://${dbhost:localhost}/roteroktober
    username: ${dbuser}
    password: ${dbpassword}
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: select 1
  jpa:
    show-sql: true
    hibernate:
      # Nötig, damit die Spaltennamen in Camel-Case geschrieben werden können
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  application:
    name: RoterOktoberServer

liquibase:
  change-log: classpath:/db/changelog/changelog.xml
  default-schema: roteroktober